### ISSUE TITLE
[Feature request] Dynamically manage users with API

### ISSUE THREAD

**Issue by betaxab** [database64128/shadowsocks-go#16]
I see you abandoned outline-ss-server, so I want to ask you, do you have any plans to develop an users API?

For example, it has the following feature:

- User additions, deletions and modifications
- User usage statistics
- Setup user usage limit

I found that the trojan-go's api is very nice:
https://p4gefau1t.github.io/trojan-go/advance/api/

Thanks.

**Comment by database64128** [comment]
Designing and maintaining a stable management API is a lot of work, and it's not particularly useful for myself. So I guess I'll just add this to the backlog and see if someday I'll feel interested enough to work on it.

**Comment by betaxab** [comment]
Thanks! Waiting for your good news.

**Comment by database64128** [comment]
A new release is out with these new features. Closing this issue.
