### ISSUE TITLE
请教如何优先走ipv4？

### ISSUE THREAD

**Issue by Tsukimeizi** [database64128/shadowsocks-go#23]
对于ipv4/ipv6双栈vps，请问如何实现除了某些域名走ipv6，其余默认走ipv4？

**Comment by database64128** [comment]
The easiest way is to build your own DNS stub resolver and use it as your system's DNS.

An imperfect solution is to always prefer IPv4 by switching to the Go resolver by adding the `GODEBUG=netdns=go` environment variable, or modifying `/etc/gai.conf` to change the system resolver's behavior.

Is there any particular reason you would like most domains to prefer IPv4? Go uses happy eyeballs by default. On your VPS, when connecting to a domain with both A and AAAA RRs, Go will race requests to both IPv6 and IPv4 with a 250ms delay.

**Comment by Tsukimeizi** [comment]
谢谢，我用的Arch Linux，修改了/etc/gai.conf (precedence ::ffff:0:0/96  100)，但ss-go仍然会优先访问IPv6地址。
我需要使用IPv6访问VPS，但是VPS的IPv6出栈路由可能有一些绕路，比如用8.8.8.8解析的youtube地址，IPv4地址的延迟在1ms左右，而IPv6地址的延迟却有50ms，所以有出栈优先IPv4的需求。

**Comment by database64128** [comment]
I used to have the same issue with Google's DNS. Switching to Cloudflare's DNS (`2606:4700:4700::1111`, `1.1.1.1`) fixed it for me.

Have you tried the environment variable I mentioned in my earlier comment? Assuming you are using my AUR package, you can edit the systemd unit file with `sudo systemctl edit shadowsocks-go` and add the following lines:

```service
[Service]
Environment=GODEBUG=netdns=go
```

The above change can be reverted by `sudo systemctl revert shadowsocks-go`.

**Comment by Tsukimeizi** [comment]
尝试修改Service文件后，仍然优先走了IPv6.
但是DNS换成1.1.1.1后解析到的IPv6地址延迟正常了。

**Comment by database64128** [comment]
Glad to hear it worked out for you. Does this mean you are now OK with shadowsocks-go preferring IPv6?

**Comment by Tsukimeizi** [comment]
Yes, that's fine. Thanks.
