### ISSUE TITLE
Difference between v2/v3?  archlinux/linux?  w or w/o CGO?

### ISSUE THREAD

**Issue by ruixingw** [database64128/shadowsocks-go#24]
> shadowsocks-go-v1.5.0-archlinux-x86-64-v2.tar.zst | Go 1.19 w/ CGO
shadowsocks-go-v1.5.0-archlinux-x86-64-v3.tar.zst | Go 1.19 w/ CGO
shadowsocks-go-v1.5.0-linux-arm64.tar.zst | Go 1.19 w/o CGO
shadowsocks-go-v1.5.0-linux-x86-64-v2.tar.zst | Go 1.19 w/o CGO
shadowsocks-go-v1.5.0-linux-x86-64-v3.tar.zst | Go 1.19 w/o CGO
shadowsocks-go-v1.5.0-windows-arm64.tar.zst | Go 1.19 w/o CGO
shadowsocks-go-v1.5.0-windows-x86-64-v2.tar.zst | Go 1.19 w/o CGO
shadowsocks-go-v1.5.0-windows-x86-64-v3.tar.zst | Go 1.19 w/o CGO

There are many release versions.. Can you explain the differences? like v2/v3, archlinux / linux, w or w/o CGO?

**Comment by database64128** [comment]
> v2/v3

https://github.com/golang/go/wiki/MinimumRequirements#amd64

> archlinux / linux, w or w/o CGO

`archlinux` binaries are built in an Arch Linux container with CGO enabled. They are linked against the current version of glibc on Arch Linux and will only run on distros with the same or a newer version of glibc.

`linux` binaries are built with CGO disabled for maximum compatibility.
