### ISSUE TITLE
Need a --version flag. 

### ISSUE THREAD

**Issue by ruixingw** [database64128/shadowsocks-go#25]
I have a `shadowsocks-go` binary, but I cannot tell what version it is.

**Comment by database64128** [comment]
For now, you can use `go version -m <binary>` to display the version info.

**Comment by database64128** [comment]
Added in 2662eb863108c6f5d384fe2db2c34ee8f2e1193c. Released with [v1.12.0](https://github.com/database64128/shadowsocks-go/releases/tag/v1.12.0).
