### ISSUE TITLE
Reload configuration without downtime

### ISSUE THREAD

**Issue by ttc0419** [database64128/shadowsocks-go#31]
Is there any way to tell the server to reload the configuration without downtime like nginx?

**Comment by database64128** [comment]
It's possible to implement it, but I'm not sure if it's really worth it. There are too many implications. How often do you need to reload the config? Which part do you want reloading to update?

**Comment by ttc0419** [comment]
Not too often.  I'm thinking of adding/removing a server configuration on the fly.

**Comment by database64128** [comment]
Not exactly what you asked for, but the latest commit added support for reloading uPSKs. Is this enough for your use case?

**Comment by ttc0419** [comment]
Yes, thanks.
