### ISSUE TITLE
How to compose domainSets files manually? 

### ISSUE THREAD

**Issue by myocytebd** [database64128/shadowsocks-go#34]
I'd like to to create some additional domain rules, but it is not obvious how to compose the first line "set capacity" and the last line "regexp:".  
shadowsocks-go-domain-set-converter does not convert to/from "obviously human-readable" format.  

(Write domains in json would be way too messy)  
(From quick test seems that "set capacity"/"regexp:" is not necessary, but I would like to get it correct)

**Comment by database64128** [comment]
> how to compose the first line "set capacity"

You don't have to write a capacity hint. It's completely optional and is meant to be generated by asking the converter to process your text file. For example, after finishing writing your rule file `test.txt`:

```bash
shadowsocks-go-domain-set-converter -inText test.txt -outText test-out.txt
```

The generated file contains a capacity hint, and the rules are deduplicated and sorted. Of course you can also change it to the gob format, which might be more efficient when there are more than a few thousand rules.

> and the last line "regexp:"

Lines not starting with a `#` are rules and are prefixed by one of the 4 type prefixes. `regexp:` is just a type prefix. You don't have to include regexp rules in your rule file. For instance, [this rule file](https://github.com/database64128/shadowsocks-go-domain-sets/blob/release/ss-go-spotify.txt) only contains a few domain and suffix rules.
