### ISSUE TITLE
Is ShadowStreamReader's ReadZeroCopy method really zerocopy?

### ISSUE THREAD

**Issue by zzzzer91** [database64128/shadowsocks-go#35]
I'm learning to use zerocopy in go, and I found this awesome project. But when I going deep on the source code  of zerocopy package, I can not find related code about zerocopy, am I wrong ? 
Thank you!

**Comment by database64128** [comment]
What kind of zerocopy are you aiming for? The purpose of the `zerocopy` package in this project is to provide a set of interfaces that help minimizing copying between different components. The outcome is that, for typical configurations, there is no copying of payload happening in userspace.

If you are talking about `SO_ZEROCOPY` and `MSG_ZEROCOPY`, I'm afraid this project does not support these.

**Comment by zzzzer91** [comment]
> What kind of zerocopy are you aiming for? The purpose of the `zerocopy` package in this project is to provide a set of interfaces that help minimizing copying between different components. The outcome is that, for typical configurations, there is no copying of payload happening in userspace.
> 
> If you are talking about `SO_ZEROCOPY` and `MSG_ZEROCOPY`, I'm afraid this project does not support these.

Ok, I get it now, thanks!
