### ISSUE TITLE
[Feature request] auto get really unix time 

### ISSUE THREAD

**Issue by never-afk** [database64128/shadowsocks-go#36]
### why we need it ?
[ss2022 wiki](https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-1-shadowsocks-2022-edition.md)
`Messages with over 30 seconds of time difference MUST be treated as replay`   

recommend add a background goroutine to get really unix time (or just once after startup) ,then we can use it  verify timestamp diff 

so we can avoid local machine time errors ?

[Public_Time_Servers](https://gist.github.com/mutin-sa/eea1c396b1e610a2da1e5550d94b0453)

**Comment by database64128** [comment]
> recommend add a background goroutine to get really unix time (or just once after startup) ,then we can use it verify timestamp diff

And now you have to detect whether the system just woke up from sleep/hibernation. Too many complications for so little benefit. Seriously, just enable NTP on your system.
