### ISSUE TITLE
Multiple users efficiency per server instance

### ISSUE THREAD

**Issue by mklnz** [database64128/shadowsocks-go#46]
Another question - regarding multiple users on each server:

Is there any benefit of running multiple server instances each with different users, compared to running just one server instance, say with a few thousand uPSK entries?

**Comment by database64128** [comment]
With multiple uPSKs on a single server, user authentication is done by decrypting an AES-encrypted block and doing a hash table lookup, which is very cheap. Of course there's the increased contention on the lock shared by the salt filter and uPSK hash map. But that's unlikely to be an issue. Generally speaking, you should be fine serving all users on a single port.

**Comment by mklnz** [comment]
I see, thanks for the prompt reply
