### ISSUE TITLE
Doesn't compatible with Go 1.22

### ISSUE THREAD

**Issue by L11R** [database64128/shadowsocks-go#55]
If you would try to build it with Go 1.22 you will get this errors:
`pkg/mod/github.com/database64128/shadowsocks-go@v1.9.0/zerocopy/tcp.go:148: undefined reference to `runtime.fastrandu'`

I hope it relates to the recent changes with `math/rand/v2` package.

**Comment by L11R** [comment]
Oh, I see fixes in master: https://github.com/database64128/shadowsocks-go/commit/93a157671b20bfaa3ff77df04a032afa1ae1d2c6
When we could wait a new release?

**Comment by database64128** [comment]
Thanks for the heads up. I'll make a new release right away.

**Comment by database64128** [comment]
The [new release](https://github.com/database64128/shadowsocks-go/releases/tag/v1.10.0) is out now.
